services:
  - type: web
    name: 90-plus
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --registry=https://registry.npmjs.org/ --package-lock=false --include=prod && npm ls socket.io
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
