(function(root){
  'use strict';
  const groups={GK:['GK'],LB:['LB','RB','CB'],RB:['RB','LB','CB'],CB:['CB','LB','RB','DM'],DM:['DM','CM','CB'],CM:['CM','DM','AM'],AM:['AM','CM','LW','RW'],LW:['LW','RW','AM','ST'],RW:['RW','LW','AM','ST'],ST:['ST','LW','RW','AM']};
  const shuffle=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
  const unique=items=>{const seen=new Set();return(items||[]).filter(item=>item?.id&&!seen.has(item.id)&&seen.add(item.id));};
  function positionScore(slot,player){if(slot===player?.position)return 10;const index=(groups[slot]||[]).indexOf(player?.position);return index<0?0:Math.max(1,7-index*2);}
  function assignPlayersToSlots(selectedPlayers,slots){const remaining=[...(selectedPlayers||[])],lineup=[];(slots||[]).forEach(slot=>{remaining.sort((a,b)=>positionScore(slot,b)-positionScore(slot,a)||(Number(b.rating)||0)-(Number(a.rating)||0));let index=remaining.findIndex(player=>positionScore(slot,player)>0);if(index<0)index=0;const[chosen]=remaining.splice(index,1);if(chosen)lineup.push({...chosen,slot});});return lineup;}
  function randomLineup(source,slots){const remaining=shuffle(unique(source)),lineup=[];(slots||[]).forEach(slot=>{const ranked=remaining.map((player,index)=>({player,index,score:positionScore(slot,player)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||Math.random()-.5);const candidates=ranked.slice(0,Math.min(8,ranked.length));const chosen=(candidates.length?candidates:remaining.map((player,index)=>({player,index})))[Math.floor(Math.random()*Math.max(1,(candidates.length||remaining.length)))];if(!chosen)return;lineup.push({...chosen.player,slot});remaining.splice(chosen.index,1);});return lineup;}
  function positionGroupMatch(player,group){if(!group)return true;if(group==='GK')return player.position==='GK';if(group==='DEF')return['LB','RB','CB'].includes(player.position);if(group==='MID')return['DM','CM','AM'].includes(player.position);if(group==='ATT')return['LW','RW','ST'].includes(player.position);return true;}
  function ratingRangeMatch(player,range){if(!range)return true;const[min,max]=String(range).split('-').map(Number);return Number(player.rating)>=min&&Number(player.rating)<=max;}
  function filterPlayers(players,criteria,periodIds,periods){const selected=(periodIds||[]).map(id=>(periods||[]).find(p=>p.id===id)).filter(Boolean);if(!selected.length)return[];return(players||[]).filter(player=>selected.some(period=>player.activeStart<=period.end&&player.activeEnd>=period.start)&&(!criteria?.nationality||player.nationality===criteria.nationality)&&(!criteria?.league||(player.leagues||[]).includes(criteria.league))&&positionGroupMatch(player,criteria?.position)&&ratingRangeMatch(player,criteria?.rating));}
  function criteriaPool(players,criteria,periodIds,periods){const sorted=filterPlayers(players,criteria,periodIds,periods).sort((a,b)=>a.rating-b.rating);if(sorted.length<=27)return sorted;const stars=sorted.filter(p=>p.rating>=86),guaranteed=shuffle(stars.slice(-Math.min(30,stars.length))).slice(0,3),ids=new Set(guaranteed.map(p=>p.id)),rest=sorted.filter(p=>!ids.has(p.id)),split=Math.ceil(rest.length/2);return unique([...shuffle(rest.slice(0,split)).slice(0,12),...shuffle(rest.slice(split)).slice(0,12),...guaranteed]).slice(0,27);}
  function candidateSet(slot,pool,usedIds){const used=usedIds||new Set(),remaining=(pool||[]).filter(p=>!used.has(p.id));const compatible=shuffle(remaining.filter(p=>positionScore(slot,p)>0)).sort((a,b)=>positionScore(slot,b)-positionScore(slot,a)||b.rating-a.rating);return unique([...compatible,...shuffle(remaining).sort((a,b)=>b.rating-a.rating)]).slice(0,Math.min(3,remaining.length));}
  root.SquadBuilder=Object.freeze({positionScore,assignPlayersToSlots,randomLineup,positionGroupMatch,ratingRangeMatch,filterPlayers,criteriaPool,candidateSet});
})(typeof window!=='undefined'?window:globalThis);
